# Generated by Django 2.1.5 on 2019-01-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comp_detect', '0003_feature_dtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
